### PR TITLE
[Feature] - LinkedIn Share

### PR DESCRIPTION
**Pull request by MrSlimCoder**
Hello contributors , I have added share to linkedin feature .

### CODE REVIEW

**Comment by MrSlimCoder** [comment]
Capture

**Comment by MrSlimCoder** [comment]
Previous PR see #28 is closed now i have sended this update PR .

**Comment by NomanGul** [comment]
@all-contributors please add @viveksharmaui for code

**Comment by NomanGul** [comment]
@viveksharmaui Thanks for your COOL contribution :rocket:

**Comment by MrSlimCoder** [comment]
@NomanGul this is just starting 🤗

**Comment by MrSlimCoder** [comment]
looking forward to contribute more on this project .

**Pull request merged**
